# Generated by Django 4.1.4 on 2022-12-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("surname", models.CharField(max_length=200)),
                (
                    "side",
                    models.CharField(
                        choices=[("1", "Jakub"), ("2", "Barbara")],
                        default="",
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
