# Generated by Django 4.1.3 on 2023-04-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("love", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Gifts",
        ),
        migrations.AddField(
            model_name="guests",
            name="bus",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
