# Generated by Django 4.1.4 on 2023-02-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("love", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gifts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
