# Generated by Django 4.1.4 on 2023-03-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("love", "0002_preferences_guests_preferences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guests",
            name="confirmation",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="guests",
            name="preferences",
            field=models.CharField(
                blank=True,
                choices=[("WEGE", "wegeterianskie"), ("MEAT", "miesne")],
                max_length=4,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="Confirmation",
        ),
        migrations.DeleteModel(
            name="Preferences",
        ),
    ]
