# Generated by Django 4.1.4 on 2023-03-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("love", "0003_alter_guests_confirmation_alter_guests_preferences_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guests",
            name="side",
            field=models.CharField(
                blank=True,
                choices=[("KUBA", "Kuba"), ("BASIA", "Basia")],
                max_length=5,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="Side",
        ),
    ]
