# Generated by Django 4.1.3 on 2023-04-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("love", "0003_guests_choice_bus"),
    ]

    operations = [
        migrations.RenameField(
            model_name="guests",
            old_name="bus",
            new_name="bus_from_b",
        ),
        migrations.AddField(
            model_name="guests",
            name="bus_from_k",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="guests",
            name="choice_bus",
            field=models.CharField(
                blank=True,
                choices=[{"BUS_B", "bus_bialystok"}, {"BUS_K", "bus_kolno"}],
                max_length=15,
                null=True,
            ),
        ),
    ]
