# Generated by Django 4.1.4 on 2023-03-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("love", "0004_alter_guests_side_delete_side"),
    ]

    operations = [
        migrations.AddField(
            model_name="guests",
            name="accompanying",
            field=models.ManyToManyField(to="love.guests"),
        ),
    ]
