# Generated by Django 4.1.3 on 2023-03-30 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("love", "0005_guests_accompanying"),
    ]

    operations = [
        migrations.AddField(
            model_name="guests",
            name="user",
            field=models.OneToOneField(
                blank=True,
                default=False,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="guests",
            name="accompanying",
            field=models.ManyToManyField(blank=True, null=True, to="love.guests"),
        ),
    ]
