# Generated by Django 4.1.3 on 2023-03-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("love", "0007_alter_guests_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="guests",
            old_name="user",
            new_name="connect",
        ),
        migrations.AlterField(
            model_name="guests",
            name="accompanying",
            field=models.ManyToManyField(blank=True, to="love.guests"),
        ),
    ]
