# Generated by Django 4.1.3 on 2023-03-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("love", "0008_rename_user_guests_connect_alter_guests_accompanying"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guests",
            name="connect",
        ),
        migrations.AlterField(
            model_name="guests",
            name="accompanying",
            field=models.ManyToManyField(blank=True, null=True, to="love.guests"),
        ),
    ]
