# Generated by Django 4.1.3 on 2023-03-31 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("love", "0009_remove_guests_connect_alter_guests_accompanying"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guests",
            name="accompanying",
            field=models.ManyToManyField(blank=True, to="love.guests"),
        ),
    ]
